.PHONY: clean All

All:
	@echo "----------Building project:[ X11menu - Debug ]----------"
	@"$(MAKE)" -f  "X11menu.mk"
clean:
	@echo "----------Cleaning project:[ X11menu - Debug ]----------"
	@"$(MAKE)" -f  "X11menu.mk" clean
